### ISSUE TITLE
CKR_TOKEN_NOT_RECOGNIZED

### ISSUE THREAD

**Issue by rhoerbe** [identinetics/keymgmt-safenetac#1]
Problem: verschiedene Tools (opensc, Java) können nicht auf den Safenet eToken 5110 zugreifen. Die Test laufen mit dem SoftHSM, aber mit dem eToken kommt die Meldung CKR_TOKEN_NOT_RECOGNIZED.

Opensc::
    ~# lsusb | grep Alladin
    > Bus 001 Device 002: ID 0529:0620 Aladdin Knowledge Systems Token JC

    ~# export PYKCS11LIB=/usr/lib64/libetvTokenEngine.so
    ~# pkcs11-tool --module $PYKCS11LIB --list-token-slots
    > Available slots:
    > Slot 0 (0x0): AKS ifdh [eToken 5110 SC] 00 00
    >   (token not recognized)

    ~# pkcs11-tool --module $PYKCS11LIB --init-token --label test --so-pin $SOPIN
    > Using slot 0 with a present token (0x0)
    > error: PKCS11 function C_GetTokenInfo failed: rv = CKR_TOKEN_NOT_RECOGNIZED (0xe1)

Getestet mit:

- Docker mit Centos 7.0, 7.1, 7.3, 7.6  (Alle opensc 0.16)
- Docker mit Centos Fedora 29 (opensc 0.19)
- Docker mit Debian Jessie (opensc 0.14)
- Centos 7.6.1810 Native

Java:

    java.io.IOException: Unable to read PKCS11 keystore
        at net.shibboleth.tool.xmlsectool.CredentialHelper.getPKCS11Credential(CredentialHelper.java:174) ~[xmlsectool-2.0.0.jar:na]
        at net.shibboleth.tool.xmlsectool.XMLSecTool.getCredential(XMLSecTool.java:901) [xmlsectool-2.0.0.jar:na]
        at net.shibboleth.tool.xmlsectool.XMLSecTool.main(XMLSecTool.java:148) [xmlsectool-2.0.0.jar:na]
    Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_201]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_201]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_201]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_201]
        at net.shibboleth.tool.xmlsectool.CredentialHelper.getPKCS11Credential(CredentialHelper.java:157) ~[xmlsectool-2.0.0.jar:na]
        ... 2 common frames omitted
    Caused by: java.security.ProviderException: Initialization failed
        at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:387) ~[sunpkcs11.jar:1.8.0_201]
        at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:103) ~[sunpkcs11.jar:1.8.0_201]
        ... 7 common frames omitted
    Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_TOKEN_NOT_RECOGNIZED
        at sun.security.pkcs11.wrapper.PKCS11.C_GetTokenInfo(Native Method) ~[sunpkcs11.jar:1.8.0_201]
        at sun.security.pkcs11.Token.<init>(Token.java:135) ~[sunpkcs11.jar:1.8.0_201]
        at sun.security.pkcs11.SunPKCS11.initToken(SunPKCS11.java:869) ~[sunpkcs11.jar:1.8.0_201]
        at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:378) ~[sunpkcs11.jar:1.8.0_201]

**Comment by rhoerbe** [comment]
I was able to intialize the device with the GUI client (Mac). Afterwards the tests passed, e.g. --list-token-slots
Available slots:
Slot 0 (0x0): AKS ifdh [eToken 5110 SC] 00 00
  token label        : Test20190418
  token manufacturer : SafeNet, Inc.
  token model        : eToken
  token flags        : login required, rng, token initialized, PIN initialized, other flags=0x200
  hardware version   : 12.0
  firmware version   : 12.0
  serial num         : 024d8da4

**Comment by rhoerbe** [comment]
sometimes the docker container needs to be recreated to have it recognize the token
